In [1]:

from audiotools import AudioSignal

# Load audio signal file
signal = AudioSignal('/raid/home/rajivratn/hemant_rajivratn/last/data/input.wav')


In [2]:
signal.shape

torch.Size([1, 1, 94480])

In [5]:
import dac
from audiotools import AudioSignal

# Download a model
model_path = dac.utils.download(model_type="16khz")
model = dac.DAC.load(model_path)

model.to('cpu')

# Encode audio signal as one long file
# (may run out of GPU memory on long files)
signal.to(model.device)

x = model.preprocess(signal.audio_data, signal.sample_rate)
z, codes, latents, _, _ = model.encode(x)


In [21]:
signal.audio_data.shape

torch.Size([1, 1, 94480])

In [35]:
import torch
m = torch.zeros(1, 4)
v = torch.randn(1, 4, 2)
# multiply mask m with v
m,v

(tensor([[0., 0., 0., 0.]]),
 tensor([[[-0.3729,  0.2726],
          [-0.1677,  0.8261],
          [-0.5999, -0.0535],
          [ 0.5582, -1.1893]]]))

In [36]:
m.unsqueeze(-1) * v

tensor([[[-0., 0.],
         [-0., 0.],
         [-0., -0.],
         [0., -0.]]])